### ISSUE TITLE
Existing BF data has differences with new source data.

### ISSUE THREAD

**Issue by gnodnooh** [HarvestStat/HarvestStat#13]
Compare Maize data (2011-2019) between new data source and raw FDW data.

Missing values and Year-off issue are reported (20240403) [[slide](https://docs.google.com/presentation/d/1IUhtj35Az75x77zcYn0JppoWrZ8dl-8130ekpNsBG5Y/edit#slide=id.g2c8e45d4f93_0_27)]

**Comment by WestonAnderson** [comment]
Following up on this, the data after 2015 is broken into different seasons and different production systems, while the data prior to this point is not. We need to combine the post-2015 data into a single "Annual" value for "All (PS)" production system (e.g sum across rainfed and irrigated, and sum across Main and Bas-Fond seasons).

**Comment by gnodnooh** [comment]
Also, I'm not sure the year-off issue is fixed in Gary's recent data.

**Comment by WestonAnderson** [comment]
I'm closing this out since it's being taken up in a Jira ticket
