### ISSUE TITLE
'planted' vs 'harvested area'

### ISSUE THREAD

**Issue by WestonAnderson** [HarvestStat/HarvestStat#39]
We should systematically decide on using 'planted' vs 'harvested area' when both are consistently available to calculate yields. We should also decide if we should report both when they are both available. How much extra work would this be in the code?

**Comment by WestonAnderson** [comment]
@gnodnooh Having reviewed where we have available Planted Area data, I think we should default to using Area Planted for all countries and use Area Harvested only when Area Planted is not available. What do you think of this approach?

**Comment by gnodnooh** [comment]
See the table of available data points:
<img width="494" alt="image" src="https://github.com/HarvestStat/HarvestStat/assets/12818281/9b17b5a5-1624-4c79-aa46-35986c23b154">

I agree with sticking with Area Planted (AP) as a default then move to Area Harvested (AH) when AP is not available. 

We also need a rule for countries where both AP and AH are available, such as Angola, Lesotho, Sudan, Somalia, Tanzania, and Zambia.

some considerations:
- (I've seen this) reported as AP in period A, then thereafter reported as AH.
- which indicator is actually used for yield calculation? (by country)

**Comment by WestonAnderson** [comment]
@gnodnooh to change the default option in the FDW sweeper to use area planted as the default rather than area harvested

**Comment by WestonAnderson** [comment]
I updated all the country scripts to default to planted area, and changed the FDW Sweeper function to default to planted area if nothing is specified

**Comment by WestonAnderson** [comment]
I updated all the country scripts to default to planted area, and changed the FDW Sweeper function to default to planted area if nothing is specified
