### ISSUE TITLE
Harvesting before planting

### ISSUE THREAD

**Issue by WestonAnderson** [HarvestStat/HarvestStat#59]
Just had a collaborator alert me that there are instances where the harvest date comes before the planting date in at least Madagascar, Malawi, Mauritania, and South Africa. I think this is where the harvest spans the calendar years and we need to amend the external crop calendar to fix this but let me know what you think.

I'll look into the problem a bit more and get some more details

**Comment by gnodnooh** [comment]
We fixed it.
